name: sms_retriever_example
description: Example app for ars_sms_retriever package
publish_to: 'none'

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  android_sms_retriever:
    path: ../

flutter:
  uses-material-design: true