name: android_sms_retriever
description: Flutter plugin for retrieving OTP code sent in sms automatically and without getting SMS permission in Android.
version: 1.3.3
homepage: https://github.com/arsamme/flutter-sms-retriever

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.arsam.sms_retriever
        pluginClass: SmsRetrieverPlugin
